Update azure-pipelines-1.yml for Azure Pipelines

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -49,58 +49,58 @@ stages:
        
     - task: Bash@3
       inputs:
-        targetType: 'inline'
-        script: |
-          #!/bin/bash
-          
-          declare -i duration=10
-          declare hasUrl=""
-          declare endpoint
-          declare -i status200count=0
-          
-          endpoint="https://openhackrm78bnn5userprofile-staging.azurewebsites.net/api/healthcheck/user"
-          
-          healthcheck() {
-              declare url=$1
-              result=$(curl -i $url 2>/dev/null | grep HTTP/1.1)
-              echo $result
-          }
-          
-          for i in {1..12}
-          do
-            result=`healthcheck $endpoint` 
-            declare status
-            echo $result
-            if [[ -z $result ]]; then  
-              status="N/A"
-              echo "Site not found"
-            else
-              status=${result:9:3}
-              timestamp=$(date "+%Y%m%d-%H%M%S")
-              if [[ -z $hasUrl ]]; then
-                echo "$timestamp | $status "
-              else
-                echo "$timestamp | $status | $endpoint " 
-              fi 
-              
-              if [ $status -eq 200 ]; then
-                ((status200count=status200count + 1))
-          
-                if [ $status200count -gt 5 ]; then
-                    break
-                fi
-              fi
-          
-              sleep $duration
-            fi
-          done
-          
-          if [ $status200count -gt 5 ]; then
-            echo "API UP"
-            # APISTATUS is a pipeline variable
-            APISTATUS="Up"
-          else
-            echo "API DOWN"
-            APISTATUS="Down"
-            exit 1;
-          fi
+       targetType: 'inline'
+       script: |
+         #!/bin/bash
+         
+         declare -i duration=10
+         declare hasUrl=""
+         declare endpoint
+         declare -i status200count=0
+         
+         endpoint="https://openhackrm78bnn5userprofile-staging.azurewebsites.net/api/healthcheck/user"
+         
+         healthcheck() {
+             declare url=$1
+             result=$(curl -i $url 2>/dev/null | grep HTTP/1.1)
+             echo $result
+         }
+         
+         for i in {1..12}
+         do
+           result=`healthcheck $endpoint` 
+           declare status
+           echo $result
+           if [[ -z $result ]]; then  
+             status="N/A"
+             echo "Site not found"
+           else
+             status=${result:9:3}
+             timestamp=$(date "+%Y%m%d-%H%M%S")
+             if [[ -z $hasUrl ]]; then
+               echo "$timestamp | $status "
+             else
+               echo "$timestamp | $status | $endpoint " 
+             fi 
+             
+             if [ $status -eq 200 ]; then
+               ((status200count=status200count + 1))
+         
+               if [ $status200count -gt 5 ]; then
+                   break
+               fi
+             fi
+         
+             sleep $duration
+           fi
+         done
+         
+         if [ $status200count -gt 5 ]; then
+           echo "API UP"
+           # APISTATUS is a pipeline variable
+           APISTATUS="Up"
+         else
+           echo "API DOWN"
+           APISTATUS="Down"
+           exit 1;
+         fi
